In [1]:
import pandas as pd
import numpy as np

In [2]:
drivers = [
    {"Driver":"Max Verstappen", 
        "Team":"Red Bull Racing", 
        "Rank": 1, 
        "Points": 575,
        "Cost":30}, 
    {"Driver":"Sergio Perez", 
        "Team":"Red Bull Racing", 
        "Rank":2, 
        "Points":285,
        "Cost":20.8}, 
    {"Driver":"Lewis Hamilton", 
        "Team":"Mercedes",
        "Rank":3,
        "Points":234,
        "Cost":19.3}, 
    {"Driver":"Fernando Alonso",
        "Team":"Aston Martin",
        "Rank":4,
        "Points":206,
        "Cost":15.8}, 
    {"Driver":"Charles Leclerc",
        "Team":"Ferrari",
        "Rank":5,
        "Points":206,
        "Cost":19.1},
    {"Driver":"Lando Norris",
        "Team":"McLaren",
        "Rank":6,
        "Points":205,
        "Cost":23.0},
    {"Driver":"Carlos Sainz",
        "Team":"Ferrari",
        "Rank":7,
        "Points":200,
        "Cost":18.5},
    {"Driver":"George Russell",
        "Team":"Mercedes",
        "Rank":8,
        "Points":175,
        "Cost":18.8},
    {"Driver":"Oscar Piastri",
        "Team":"McLaren",
        "Rank":9,
        "Points":97,
        "Cost":19.0},
    {"Driver":"Lance Stroll",
        "Team":"Aston Martin",
        "Rank":10,
        "Points":74,
        "Cost":10.7},
    {"Driver":"Pierre Gasly",
        "Team":"Alpine",
        "Rank":11,
        "Points":62,
        "Cost":7.8},
    {"Driver":"Esteban Ocon",
        "Team":"Alpine",
        "Rank":12,
        "Points":58,
        "Cost":7.8},
    {"Driver":"Alexander Albon",
        "Team":"Williams",
        "Rank":13,
        "Points":27,
        "Cost":7.0},
    {"Driver":"Yuki Tsunoda",
        "Team":"RB",
        "Rank":14,
        "Points":17,
        "Cost":8.0},
    {"Driver":"Valtteri Bottas",
        "Team":"Stake",
        "Rank":15,
        "Points":10,
        "Cost":6.4},
    {"Driver":"Nico Hulkenberg",
        "Team":"Haas",
        "Rank":16,
        "Points":9,
        "Cost":6.4},
    {"Driver":"Daniel Ricciardo",
        "Team":"RB",
        "Rank":17,
        "Points":6,
        "Cost":9.0},
    {"Driver":"Zhou Guanyu",
        "Team":"Stake",
        "Rank":18,
        "Points":6,
        "Cost":6.6},
    {"Driver":"Kevin Magnussen",
        "Team":"Haas",
        "Rank":19,
        "Points":3,
        "Cost":6.2},
    {"Driver":"Logan Sargeant",
        "Team":"Williams",
        "Rank":20,
        "Points":1,
        "Cost":5.5}
]

In [3]:
df = pd.DataFrame(drivers)

In [4]:
df

              Driver             Team  Rank  Points  Cost
0     Max Verstappen  Red Bull Racing     1     575  30.0
1       Sergio Perez  Red Bull Racing     2     285  20.8
2     Lewis Hamilton         Mercedes     3     234  19.3
3    Fernando Alonso     Aston Martin     4     206  15.8
4    Charles Leclerc          Ferrari     5     206  19.1
5       Lando Norris          McLaren     6     205  23.0
6       Carlos Sainz          Ferrari     7     200  18.5
7     George Russell         Mercedes     8     175  18.8
8      Oscar Piastri          McLaren     9      97  19.0
9       Lance Stroll     Aston Martin    10      74  10.7
10      Pierre Gasly           Alpine    11      62   7.8
11      Esteban Ocon           Alpine    12      58   7.8
12   Alexander Albon         Williams    13      27   7.0
13      Yuki Tsunoda               RB    14      17   8.0
14   Valtteri Bottas            Stake    15      10   6.4
15   Nico Hulkenberg             Haas    16       9   6.4
16  Daniel Ricciardo               RB    17       6   9.0
17       Zhou Guanyu            Stake    18       6   6.6
18   Kevin Magnussen             Haas    19       3   6.2
19    Logan Sargeant         Williams    20       1   5.5

In [5]:
np.log1p(2)

1.0986122886681096

In [6]:
df['value'] = (np.log1p(df["Points"])/np.log1p(1.1) + 10*1/(df["Rank"]+1))/df["Cost"] * 100
df['value2'] = (np.log1p(df["Points"]/np.log1p(2))/df["Cost"])*10
df['raw value'] = (df["Points"] + 10*(1/(df["Rank"] + 1)))/df["Cost"]

In [7]:
df['subtract value'] = (df["Points"] - 0.1*df["Points"] + 10*(1/(df["Rank"] + 1)))/df["Cost"]

In [8]:
df.sort_values(by = ["subtract value"], ascending=False)

,Driver,Team,Rank,Points,Cost,value,value2,raw value,subtract value
0,Max Verstappen,Red Bull Racing,1,575,30.0,45.223021,2.087410,19.333333,17.416667
1,Sergio Perez,Red Bull Racing,2,285,20.8,52.675998,2.674177,13.862179,12.491987
3,Fernando Alonso,Aston Martin,4,206,15.8,58.149111,3.315916,13.164557,11.860759
2,Lewis Hamilton,Mercedes,3,234,19.3,51.080587,2.780289,12.253886,11.041451
6,Carlos Sainz,Ferrari,7,200,18.5,45.394134,2.816080,10.878378,9.797297
4,Charles Leclerc,Ferrari,5,206,19.1,46.357205,2.743009,10.872600,9.794066
7,George Russell,Mercedes,8,175,18.8,42.978760,2.700530,9.367612,8.436761
5,Lando Norris,McLaren,6,205,23.0,37.433060,2.275786,8.975155,8.083851
10,Pierre Gasly,Alpine,11,62,7.8,82.276210,5.193142,8.055556,7.260684
11,Esteban Ocon,Alpine,12,58,7.8,80.320876,5.109179,7.534517,6.790927
9,Lance Stroll,Aston Martin,10,74,10.7,62.881303,3.948368,7.000850,6.309261
8,Oscar Piastri,McLaren,9,97,19.0,37.788017,2.364171,5.157895,4.647368
12,Alexander Albon,Williams,13,27,7.0,74.364380,4.630961,3.959184,3.573469
13,Yuki Tsunoda,RB,14,17,8.0,57.029692,3.502234,2.208333,1.995833
14,Valtteri Bottas,Stake,15,10,6.4,60.264652,3.613707,1.660156,1.503906
15,Nico Hulkenberg,Haas,16,9,6.4,57.682996,3.466172,1.498162,1.357537
17,Zhou Guanyu,Stake,18,6,6.6,47.712995,2.827048,0.988836,0.897927
16,Daniel Ricciardo,RB,17,6,9.0,35.314416,2.073168,0.728395,0.661728
18,Kevin Magnussen,Haas,19,3,6.2,38.201274,2.123549,0.564516,0.516129
19,Logan Sargeant,Williams,20,1,5.5,25.644182,1.176779,0.268398,0.250216

In [9]:
# picking the optimal team
df['Type'] = "Driver"

pick an optimal team

+ at each step, pick the highest value of a driver
+ subtract from the budget.

In [10]:
team_vals = df.groupby('Team')['raw value'].sum()

In [11]:
team_vals.sort_values(ascending=False)

Team
Red Bull Racing    33.195513
Ferrari            21.750979
Mercedes           21.621498
Aston Martin       20.165407
Alpine             15.590072
McLaren            14.133050
Williams            4.227582
RB                  2.936728
Stake               2.648992
Haas                2.062678
Name: raw value, dtype: float64

In [12]:
team_vals = team_vals/team_vals.sum()

In [13]:
team_costs = [
    {'Team':'Red Bull Racing','Cost':27.9},
    {'Team':'McLaren','Cost':23.2},
    {'Team':'Mercedes','Cost':20.1},
    {'Team':'Ferrari','Cost':19.3},
    {'Team':'Aston Martin','Cost':13.6},
    {'Team':'RB','Cost':8.5},
    {'Team':'Alpine','Cost':8.4},
    {'Team':'Stake','Cost':6.6},
    {'Team':'Williams','Cost':6.3},
    {'Team':'Haas','Cost':6.3}
]

In [14]:
team_points = df.groupby('Team')['Points'].sum().reset_index()
team_points

              Team  Points
0           Alpine     120
1     Aston Martin     280
2          Ferrari     406
3             Haas      12
4          McLaren     302
5         Mercedes     409
6               RB      23
7  Red Bull Racing     860
8            Stake      16
9         Williams      28

In [15]:
help(pd.DataFrame.merge)

Help on function merge in module pandas.core.frame:

merge(self, right: 'DataFrame | Series', how: 'MergeHow' = 'inner', on: 'IndexLabel | AnyArrayLike | None' = None, left_on: 'IndexLabel | AnyArrayLike | None' = None, right_on: 'IndexLabel | AnyArrayLike | None' = None, left_index: 'bool' = False, right_index: 'bool' = False, sort: 'bool' = False, suffixes: 'Suffixes' = ('_x', '_y'), copy: 'bool | None' = None, indicator: 'str | bool' = False, validate: 'MergeValidate | None' = None) -> 'DataFrame'
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
    on : label or list
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : label or list, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : label or list, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default True
        If False, avoid copy if possible.

        .. note::
            The `copy` keyword will change behavior in pandas 3.0.
            `Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            will be enabled by default, which means that all methods with a
            `copy` keyword will use a lazy copy mechanism to defer the copy and
            ignore the `copy` keyword. The `copy` keyword will be removed in a
            future version of pandas.

            You can already get the future behavior and improvements through
            enabling copy on write ``pd.options.mode.copy_on_write = True``
    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  bar        2  bar        6
    3  baz        3  baz        7
    4  foo        5  foo        5
    5  foo        5  foo        8

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  bar           2  bar            6
    3  baz           3  baz            7
    4  foo           5  foo            5
    5  foo           5  foo            8

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8

In [16]:
team_costs = pd.DataFrame(team_costs)
team_points = df.groupby('Team')['Points'].sum().reset_index()
team_costs = team_costs.merge(team_points, 
                              left_on='Team', 
                              right_on='Team', 
                              how='inner')
team_costs['raw value'] = team_costs["Points"]/team_costs['Cost']
team_costs = team_costs.sort_values(by=['raw value'], ascending=False)
team_costs['Type'] = "Team"

In [17]:
team_vals.sort_values(ascending=False)

Team
Red Bull Racing    0.239969
Ferrari            0.157237
Mercedes           0.156301
Aston Martin       0.145775
Alpine             0.112700
McLaren            0.102167
Williams           0.030561
RB                 0.021229
Stake              0.019149
Haas               0.014911
Name: raw value, dtype: float64

In [18]:
team_costs.rename(columns={'Team':'Item'}, inplace=True)
df.rename(columns={'Driver':'Item'},inplace=True)

optimization_vals = pd.concat([team_costs[['Item','raw value','Cost', 'Type']], 
                              df[['Item','raw value','Cost','Type']]])

In [19]:
optimization_vals.sort_values(by=['raw value'], ascending=False)

                Item  raw value  Cost    Type
0    Red Bull Racing  30.824373  27.9    Team
3            Ferrari  21.036269  19.3    Team
4       Aston Martin  20.588235  13.6    Team
2           Mercedes  20.348259  20.1    Team
0     Max Verstappen  19.333333  30.0  Driver
6             Alpine  14.285714   8.4    Team
1       Sergio Perez  13.862179  20.8  Driver
3    Fernando Alonso  13.164557  15.8  Driver
1            McLaren  13.017241  23.2    Team
2     Lewis Hamilton  12.253886  19.3  Driver
6       Carlos Sainz  10.878378  18.5  Driver
4    Charles Leclerc  10.872600  19.1  Driver
7     George Russell   9.367612  18.8  Driver
5       Lando Norris   8.975155  23.0  Driver
10      Pierre Gasly   8.055556   7.8  Driver
11      Esteban Ocon   7.534517   7.8  Driver
9       Lance Stroll   7.000850  10.7  Driver
8      Oscar Piastri   5.157895  19.0  Driver
8           Williams   4.444444   6.3    Team
12   Alexander Albon   3.959184   7.0  Driver
5                 RB   2.705882   8.5    Team
7              Stake   2.424242   6.6    Team
13      Yuki Tsunoda   2.208333   8.0  Driver
9               Haas   1.904762   6.3    Team
14   Valtteri Bottas   1.660156   6.4  Driver
15   Nico Hulkenberg   1.498162   6.4  Driver
17       Zhou Guanyu   0.988836   6.6  Driver
16  Daniel Ricciardo   0.728395   9.0  Driver
18   Kevin Magnussen   0.564516   6.2  Driver
19    Logan Sargeant   0.268398   5.5  Driver

In [20]:
team1 = {"Max Verstappen", "Daniel Ricciardo",
         "Valtteri Bottas", "Logan Sargeant", 
         "Sergio Perez", "RB", "Ferrari"}
team2 = {"Max Verstappen", "Carlos Sainz", 
         "Alexander Albon", "Fernando Alonso", 
         "Logan Sargeant", "Aston Martin", "RB"}

In [21]:
score1 = 0
print("---team1---")
for item in team1: 
    val = optimization_vals.loc[optimization_vals["Item"] == item, "raw value"]
    print(item)
    print(val.values)
    score1 += val.values[0]

score2 = 0
print("---team2---")
for item in team2:
    val = optimization_vals.loc[optimization_vals["Item"] == item, "raw value"]
    print(item)
    print(val.values)
    score2 += val.values[0]

print("Score 1: {} \nScore 2: {}".format(score1, score2))

---team1---
Daniel Ricciardo
[0.72839506]
Logan Sargeant
[0.26839827]
Valtteri Bottas
[1.66015625]
Sergio Perez
[13.86217949]
RB
[2.70588235]
Ferrari
[21.03626943]
Max Verstappen
[19.33333333]
---team2---
Logan Sargeant
[0.26839827]
Carlos Sainz
[10.87837838]
Alexander Albon
[3.95918367]
RB
[2.70588235]
Aston Martin
[20.58823529]
Fernando Alonso
[13.16455696]
Max Verstappen
[19.33333333]
Score 1: 59.59461418363247
Score 2: 70.89796826266351

In [22]:
optimization_vals.loc[optimization_vals["Item"]=="Max Verstappen", "raw value"].values[0]

19.333333333333332

In [23]:
for index, row in optimization_vals.iterrows(): 
    print(row)
    print()

Item         Red Bull Racing
raw value          30.824373
Cost                    27.9
Type                    Team
Name: 0, dtype: object

Item           Ferrari
raw value    21.036269
Cost              19.3
Type              Team
Name: 3, dtype: object

Item         Aston Martin
raw value       20.588235
Cost                 13.6
Type                 Team
Name: 4, dtype: object

Item          Mercedes
raw value    20.348259
Cost              20.1
Type              Team
Name: 2, dtype: object

Item            Alpine
raw value    14.285714
Cost               8.4
Type              Team
Name: 6, dtype: object

Item           McLaren
raw value    13.017241
Cost              23.2
Type              Team
Name: 1, dtype: object

Item         Williams
raw value    4.444444
Cost              6.3
Type             Team
Name: 8, dtype: object

Item               RB
raw value    2.705882
Cost              8.5
Type             Team
Name: 5, dtype: object

Item            Stake
raw value    2.424242
Cost              6.6
Type             Team
Name: 7, dtype: object

Item             Haas
raw value    1.904762
Cost              6.3
Type             Team
Name: 9, dtype: object

Item         Max Verstappen
raw value         19.333333
Cost                   30.0
Type                 Driver
Name: 0, dtype: object

Item         Sergio Perez
raw value       13.862179
Cost                 20.8
Type               Driver
Name: 1, dtype: object

Item         Lewis Hamilton
raw value         12.253886
Cost                   19.3
Type                 Driver
Name: 2, dtype: object

Item         Fernando Alonso
raw value          13.164557
Cost                    15.8
Type                  Driver
Name: 3, dtype: object

Item         Charles Leclerc
raw value            10.8726
Cost                    19.1
Type                  Driver
Name: 4, dtype: object

Item         Lando Norris
raw value        8.975155
Cost                 23.0
Type               Driver
Name: 5, dtype: object

Item         Carlos Sainz
raw value       10.878378
Cost                 18.5
Type               Driver
Name: 6, dtype: object

Item         George Russell
raw value          9.367612
Cost                   18.8
Type                 Driver
Name: 7, dtype: object

Item         Oscar Piastri
raw value         5.157895
Cost                  19.0
Type                Driver
Name: 8, dtype: object

Item         Lance Stroll
raw value         7.00085
Cost                 10.7
Type               Driver
Name: 9, dtype: object

Item         Pierre Gasly
raw value        8.055556
Cost                  7.8
Type               Driver
Name: 10, dtype: object

Item         Esteban Ocon
raw value        7.534517
Cost                  7.8
Type               Driver
Name: 11, dtype: object

Item         Alexander Albon
raw value           3.959184
Cost                     7.0
Type                  Driver
Name: 12, dtype: object

Item         Yuki Tsunoda
raw value        2.208333
Cost                  8.0
Type               Driver
Name: 13, dtype: object

Item         Valtteri Bottas
raw value           1.660156
Cost                     6.4
Type                  Driver
Name: 14, dtype: object

Item         Nico Hulkenberg
raw value           1.498162
Cost                     6.4
Type                  Driver
Name: 15, dtype: object

Item         Daniel Ricciardo
raw value            0.728395
Cost                      9.0
Type                   Driver
Name: 16, dtype: object

Item         Zhou Guanyu
raw value       0.988836
Cost                 6.6
Type              Driver
Name: 17, dtype: object

Item         Kevin Magnussen
raw value           0.564516
Cost                     6.2
Type                  Driver
Name: 18, dtype: object

Item         Logan Sargeant
raw value          0.268398
Cost                    5.5
Type                 Driver
Name: 19, dtype: object

In [24]:
def knapSack_Team(Types=Weight=100, num_teams=2, num_drivers=5, Items=None):
    drives_rem = num_drivers
    teams_rem = num_teams

    final_team = []
    for index, row in Items.iterrows():
        if not (row['Type'] == 'Driver' and drives_rem - 1 > 0):
            continue
        if not (row['Type'] == 'Team' and teams_rem - 1 > 0):
            continue
        if not

SyntaxError: invalid syntax (4245440207.py, line 1)

In [ ]:
class opt_val:
    def __init__(self, item, raw_val, cost, item_type):
        self.item = item
        self.raw_val = raw_val
        self.cost = cost
        self.type = item_type

    def __str__(self):
        return "{} {} {} {}".format(self.item, self.raw_val, self.cost, self.type)

In [ ]:
# create list of opt_val types to iterate through
opt_vals = dict()

for index, row in optimization_vals.iterrows():
    opt_vals[row['Item']] = opt_val(row['Item'], row['raw value'], row['Cost'], row['Type'])

In [ ]:
opt_vals

{'Red Bull Racing': <__main__.opt_val at 0x7fd9c7b34290>,
 'Ferrari': <__main__.opt_val at 0x7fd9c7b348f0>,
 'Aston Martin': <__main__.opt_val at 0x7fd9c7b344a0>,
 'Mercedes': <__main__.opt_val at 0x7fd9c7b34590>,
 'Alpine': <__main__.opt_val at 0x7fd9c7b348c0>,
 'McLaren': <__main__.opt_val at 0x7fd9c7b34050>,
 'Williams': <__main__.opt_val at 0x7fd9c7b34e00>,
 'RB': <__main__.opt_val at 0x7fd9c7b351f0>,
 'Stake': <__main__.opt_val at 0x7fd9c7b34ec0>,
 'Haas': <__main__.opt_val at 0x7fd9c7b34da0>,
 'Max Verstappen': <__main__.opt_val at 0x7fd9c7b34c20>,
 'Sergio Perez': <__main__.opt_val at 0x7fd9c7b346e0>,
 'Lewis Hamilton': <__main__.opt_val at 0x7fd9c7b34bc0>,
 'Fernando Alonso': <__main__.opt_val at 0x7fd9c7b34b00>,
 'Charles Leclerc': <__main__.opt_val at 0x7fd9c7b34890>,
 'Lando Norris': <__main__.opt_val at 0x7fd9c7b34f80>,
 'Carlos Sainz': <__main__.opt_val at 0x7fd9c7b34a40>,
 'George Russell': <__main__.opt_val at 0x7fd9c7b35250>,
 'Oscar Piastri': <__main__.opt_val at 0x7fd9c7b34ef0>,
 'Lance Stroll': <__main__.opt_val at 0x7fd9c7b35370>,
 'Pierre Gasly': <__main__.opt_val at 0x7fd9c7b352e0>,
 'Esteban Ocon': <__main__.opt_val at 0x7fd9c7b34800>,
 'Alexander Albon': <__main__.opt_val at 0x7fd9c7b35460>,
 'Yuki Tsunoda': <__main__.opt_val at 0x7fd9c7b35400>,
 'Valtteri Bottas': <__main__.opt_val at 0x7fd9c7b352b0>,
 'Nico Hulkenberg': <__main__.opt_val at 0x7fd9c7b354f0>,
 'Daniel Ricciardo': <__main__.opt_val at 0x7fd9c7b35760>,
 'Zhou Guanyu': <__main__.opt_val at 0x7fd9c7b356a0>,
 'Kevin Magnussen': <__main__.opt_val at 0x7fd9c7b35550>,
 'Logan Sargeant': <__main__.opt_val at 0x7fd9c7b35820>}

In [ ]:
solved_solutions = pd.DataFrame(columns=['weight','num_teams','num_drivers','score'])

# solution will hold a list of dataframe tuples
def recur_team(weight=100, num_teams=2, num_drivers=5, Items=None, solution=0, solved_solutions=solved_solutions):
    if (num_teams==0) and (num_drivers==0):
        solved_solutions = pd.concat([solved_solutions, 
                                     pd.DataFrame([{'weight':weight,
                                                   'num_teams':num_teams,
                                                   'num_drivers':num_drivers,
                                                   'score':solution}])])
        return solution, solved_solutions
    elif (weight < 0 and ((num_drivers > 0) or (num_teams > 0))):
        return -1, solved_solutions
    
    # return a memoized solution
    if ((solved_solutions['weight']==weight) & 
        (solved_solutions['num_teams']==num_teams) & 
        (solved_solutions['num_drivers']==num_drivers)).any():
        return solved_solutions.loc[('weight'==weight) & ('num_teams'==num_teams) & ('num_drivers'==num_drivers), 'score'], solved_solutions

    max_solution = solution
    for item in opt_vals:
        if opt_vals[item].type == "Driver":
            partial_sol, solved_solutions = recur_team(weight=weight-opt_vals[item].cost, 
                                                       num_drivers=num_drivers-1,
                                                       num_teams=num_teams, 
                                                       solution=solution+opt_vals[item].raw_val)
        else:
            partial_sol, solved_solutions = recur_team(weight=weight-opt_vals[item].cost, 
                                                       num_drivers=num_drivers,
                                                       num_teams=num_teams-1,
                                                       solution=solution+opt_vals[item].raw_val)
        if partial_sol == -1: continue

        if partial_sol > max_solution: max_solution=partial_sol

    solved_solutions = pd.concat([solved_solutions, 
                                 pd.DataFrame([{'weight':weight,
                                               'num_teams':num_teams,
                                               'num_drivers':num_drivers,
                                               'score':solution}])])

    return max_solution, solved_solutions

Come up with a system for retrieving data about the scores and rankings from previous races and automatically compiling a driver valuation rating for that driver.